FROM node:20-alpine

# 安装pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

# 复制package.json和lock文件
COPY package.json pnpm-lock.yaml ./

# 安装依赖
RUN pnpm install

# 复制其余源代码
COPY . .

ENV STRAPI_URL=http://host.docker.internal:1337

# 暴露端口
EXPOSE 3000

# 开发模式启动命令
CMD ["pnpm", "dev"]