import '@/styles/globals.css'

import type { Metadata } from 'next'

import { geistMono, geistSans } from '@/styles/fonts'

import Footer from './_components/footer'
import Header from './_components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
